# Generated by Django 5.2.8 on 2025-11-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_multiple_votes', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'is_active'], name='polls_poll_created_4ca8e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_identifier', models.CharField(db_index=True, max_length=255)),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
            ],
            options={
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['poll', '-vote_count'], name='polls_optio_poll_id_625969_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('poll', 'text')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option', 'voter_identifier'], name='polls_vote_option__77a8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_identifier', '-voted_at'], name='polls_vote_voter_i_b3d8fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('option', 'voter_identifier')},
        ),
    ]
